"""initial schema

Revision ID: ed3b002797bb
Revises: 
Create Date: 2026-09-23 09:55:09.628120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed3b002797bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('ai_request_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('request_type', sa.String(length=30), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_request_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_request_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_request_logs_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_request_logs_user_id'), ['user_id'], unique=False)

    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_subject_id'), ['subject_id'], unique=False)

    op.create_table('lesson_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_path', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_documents_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_documents_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_score', sa.Float(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_progress_user_lesson')
    )
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_user_id'), ['user_id'], unique=False)

    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('student_review_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_review_user_lesson')
    )
    with op.batch_alter_table('student_review_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_review_schedules_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_review_schedules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_review_schedules_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_review_schedules_user_id'), ['user_id'], unique=False)

    op.create_table('student_weaknesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('last_mistake_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', 'topic', name='uq_weakness_user_lesson_topic')
    )
    with op.batch_alter_table('student_weaknesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_weaknesses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_weaknesses_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_weaknesses_user_id'), ['user_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['lesson_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_lesson_id'), ['lesson_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.String(length=500), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total_points', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('points_earned', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_answer_attempt_question')
    )
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_answers_question_id'), ['question_id'], unique=False)

    op.create_table('student_mistakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('mistake_key', sa.String(length=100), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mistake_key', name='uq_mistake_user_key')
    )
    with op.batch_alter_table('student_mistakes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_mistakes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_mistakes_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_mistakes_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_mistakes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_mistakes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_mistakes_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_mistakes_question_id'))
        batch_op.drop_index(batch_op.f('ix_student_mistakes_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_student_mistakes_id'))

    op.drop_table('student_mistakes')
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_answers_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_answers_attempt_id'))

    op.drop_table('quiz_answers')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_id'))

    op.drop_table('quiz_attempts')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_questions_id'))

    op.drop_table('questions')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_id'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))

    op.drop_table('document_chunks')
    with op.batch_alter_table('student_weaknesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_weaknesses_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_weaknesses_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_student_weaknesses_id'))

    op.drop_table('student_weaknesses')
    with op.batch_alter_table('student_review_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_review_schedules_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_review_schedules_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_student_review_schedules_id'))
        batch_op.drop_index(batch_op.f('ix_student_review_schedules_due_at'))

    op.drop_table('student_review_schedules')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_quizzes_id'))

    op.drop_table('quizzes')
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_id'))

    op.drop_table('lesson_progress')
    with op.batch_alter_table('lesson_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_documents_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_documents_id'))

    op.drop_table('lesson_documents')
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_subject_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('ai_request_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_request_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_request_logs_lesson_id'))
        batch_op.drop_index(batch_op.f('ix_ai_request_logs_id'))

    op.drop_table('ai_request_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_id'))

    op.drop_table('subjects')
    # ### end Alembic commands ###
